### PR TITLE
add project M

### PR DESCRIPTION
**Pull request by 486DX2**
Hi

Can you add Project M visualisation to audacious please?

Thx

### CODE REVIEW

**Comment by jlindgren90** [comment]
I don't understand what's going on with the commits in this MR (they look like old commits already in the repo?) and they don't seem related to the subject.

**Comment by 486DX2** [comment]
Add Project M visualisation!
What's not to understand about this?

**Comment by radioactiveman** [comment]
GitHub pull requests are intended for developers who want to integrate their code changes into the main project.

For a general feature request feel free to create one in our [bug tracker](https://redmine.audacious-media-player.org/).

**Comment by 486DX2** [comment]
you close issues here and make a different bug tracker
that's like inventing the wheel again...

**Comment by 486DX2** [comment]
Why are issues disabled here on github?

**Comment by mschwendt** [comment]
> Why are issues disabled here on github?

Since there is the developers' own preferred bug tracker based on Redmine, it would not make sense to enable a secondary bug tracking system at github. It would lead to chaos and extra maintenance burden, such as more duplicates and the wish to link/forward tickets between two competing bug trackers.

**Pull request closed without merging**
