### PR TITLE
Added "makeitpersonal.co" lyrics provider

### PR DESCRIPTION
**Pull request by ManuLinares**
Added a new lyrics provider, and set it to default as provides more accurate and extensive lyrics.

### CODE REVIEW

**Comment by jlindgren90** [comment]
It would be nice to have some more background about who runs `makeitpersonal.co`, terms of use, copyright, etc.

**Comment by ManuLinares** [comment]
The source code: https://github.com/febuiles/makeitpersonal
https://makeitpersonal.co/disclaimer
https://makeitpersonal.co/manifesto

Maybe directly contact the developer on https://makeitpersonal.co/contact
`Hi. If you have any questions, lawsuits or death threats please send an email to [federico@mheroin.com](mailto:federico@mheroin.com).`

----

Another one we can use is "http://chartlyrics.com" api. 
Here are the "Terms of Use" at the bottom of the page http://www.chartlyrics.com/api.aspx

Example:

`curl "http://api.chartlyrics.com/apiv1.asmx/SearchLyricDirect?artist=foo%20fighters&song=everlong"`

**Comment by jlindgren90** [comment]
Thanks for the additional information.

From https://blog.makeitpersonal.co/:
> I don’t know anything about the legal issues surrounding lyrics’ copyrights once they’re modified by somebody else (which is what we do on makeitpersonal.

From what I can understand, `makeitpersonal.co` seems to try to avoid copyright issues by *not* hosting the exact/original lyrics of the song, but modified versions. (I guess that's what "makes it personal"?) I don't think that's what we are looking for in a lyrics provider, certainly not in the default one.

> If you are a non-commercial entity (eg. an individual) and you are not charging for your product, **and the product has no other commercial purpose**, then you can use the ChartLyrics APIs. Otherwise, you will require our written permission. [emphasis added]

That rules out using `chartlyrics.com` in Audacious. Audacious can be used (and does get used) for commercial purposes.

**Comment by ManuLinares** [comment]
Makeitpersonal doesn't change lyrics even if it says so. I'll upload a test diff script.

My two cents: I'm no legal expert but Audacious meets the "you are not charging for your product" and "the product has no other commercial purpose" criteria.
Audacious/Plugins have no commercial purpose. (A person can find commercial potential in any two lines of code found on stackoverflow or github)

I don't know what **lyrics.ovh** is doing better legally but I found no info.

Anyway, legal issues confuse me and also putting "Nowhere" in the list of lyrics providers. (I thought it was a provider 😊).

I don't know how to proceed. There are many, many public API's for lyrics, I found the two simpler ones that have a large database.

**Comment by radioactiveman** [comment]
My opinion/recommendation is:

1. `makeitpersonal.co`: Fine to add for me, but don't set it as default. But please check if the lyrics get indeed modified.
2. `chartlyrics.com`: Why not contact them and ask if Audacious can use the service for free as BSD licensed project which may be used commercially? If they give us the permission in written form (email), you can of course add the provider code for it.

> Audacious can be used (and does get used) for commercial purposes.

@jlindgren90: Can you please give more information about the "does get used"? That interests me in general, independent from the lyric license topic discussed here.

**Comment by jlindgren90** [comment]
Regarding commercial use, we've had users mention using Audacious in a DJ setup and for theater (sound effects). If someone wants to get in touch with chartlyrics.com and ask permission, that's fine.

**Comment by ManuLinares** [comment]
Simple script that check lyric differences between services.

```
#!/bin/bash
# Usage: ./diff_songs.sh file.csv
#
# Reads a list of "artist,song" csv, downloads lyrics and compares with diff.
# Skips not found lyrics

# Check parameters
if [ "$#" -ne 1 ]; then
     >&2 echo -e "Illegal number of parameters\n  Usage: ./diff_songs.sh songlist.csv"
    exit 1
fi

# Check file
if [ ! -f "${1}" ]; then
     >&2 echo "File ${1} not found"
    exit 1
fi

FILE="${1}"

while read -r line; do
    ARTIST=$(echo "${line}" | cut -d"," -f1)
    TITLE=$(echo "${line}" | cut -d"," -f2)

	a=$(curl -s "http://api.chartlyrics.com/apiv1.asmx/SearchLyricDirect?artist=${ARTIST/ /%20}&song=${TITLE/ /%20}" | awk 'BEGIN{RS="</Lyric>"; FS="<Lyric>"}NF>1{print $NF}')
	b=$(curl -s "https://makeitpersonal.co/lyrics?artist=${ARTIST/ /%20}&title=${TITLE/ /%20}")

	
	[[ $b == *"Sorry, We don't have lyrics for this song yet."* ]] && continue; 
	
	printf '| %35s |'  "${ARTIST/%20/ }" "${TITLE/%20/ }" "Differences: "
	diff --suppress-blank-empty -i -Z -b -w -B <(echo "$a") <(echo "$b") | wc -l

done < "${FILE}"
```

Rolling Stone - 500 Greatest Songs ([source](https://cs.uwaterloo.ca/~dtompkin/music/list/Best9.html))
[songlist.csv](https://github.com/audacious-media-player/audacious-plugins/files/10291282/songlist.csv)

**Comment by radioactiveman** [comment]
I have tested this yesterday and today again. It looks like the `makeitpersonal` API has been disabled meanwhile and always returns:

```
Bots have beat this API for the time being, sorry!
```

@ManuLinares: Do you want to get in touch with them and sort this out? But in general I don't think it makes sense to add this API if it is unreliable. Thanks anyway for your contribution. :+1:

**Comment by radioactiveman** [comment]
makeitpersonal.co is still returning the same error response, therefore I close this PR.
```
Bots have beat this API for the time being, sorry!
```

**Pull request closed without merging**
