### PR TITLE
statusicon-qt: Set proper tooltip

### PR DESCRIPTION
**Pull request by radioactiveman**
Even though we override the QSystemTrayIcon::event() method,
it is never called by Qt (at least on Linux when the panel/DE
supports StatusNotifierItem). Therefore our custom info popup
is not shown. Set a proper tooltip as workaround.

### CODE REVIEW

**Comment by radioactiveman** [comment]
@jlindgren90: Why is the `title_changed()` method never called? What am I missing here? It is registered to the hook and there is no typo.

**Comment by jlindgren90** [comment]
> @jlindgren90: Why is the `title_changed()` method never called? What am I missing here? It is registered to the hook and there is no typo.

"title change" is for streaming when the title changes mid-stream. To get the initial title you can use "playback ready" (if memory serves).

**Comment by radioactiveman** [comment]
Thanks, updated accordingly.

One more question: I wonder if there is a difference regarding number of memory allocations and preventing memory leaks between these options. Which would you choose?

```c++
const char * title = aud_drct_get_title ();
tray->setToolTip (title);
```

```c++
String title = aud_drct_get_title ();
tray->setToolTip ((const char *) title);
```

```c++
String title = aud_drct_get_title ();
tray->setToolTip (QString (title));
```

**Comment by jlindgren90** [comment]
> One more question: I wonder if there is a difference regarding number of memory allocations and preventing memory leaks between these options. Which would you choose?
> 
> ```c++
> const char * title = aud_drct_get_title ();
> tray->setToolTip (title);
> ```
> 
> ```c++
> String title = aud_drct_get_title ();
> tray->setToolTip ((const char *) title);
> ```
> 
> ```c++
> String title = aud_drct_get_title ();
> tray->setToolTip (QString (title));
> ```

The first one is unsafe since the String will go out of scope too early (leaving a dangling pointer). The last two are equivalent so either one is fine.

**Comment by jlindgren90** [comment]
Thanks for working on this. Have you checked how this works with a panel/desktop environment supporting only XEmbed? Do we end up showing a double tooltip/info popup in that case?

**Comment by radioactiveman** [comment]
> Thanks for working on this. Have you checked how this works with a panel/desktop environment supporting only XEmbed? Do we end up showing a double tooltip/info popup in that case?

I have tested it with Xfce and GNOME. Xfce has shown a tooltip also before ("Audacious") which is rather useless. GNOME with this [extension](https://extensions.gnome.org/extension/615/appindicator-support/) neither shows a tooltip nor the info popup. Next week I can test how macOS behaves.

Which panel / DE do you use? Could you please test it yourself too?

**Comment by radioactiveman** [comment]
@bpanca05: In your [bug report](https://github.com/orgs/audacious-media-player/discussions/93) I have seen you use KDE and also enabled the status icon plugin. Could you please answer my questions and try the patch from this pull request?

- Does KDE show the info popup like in my screenshot below, a general tooltip like "Audacious" or no tooltip at all?
- Does changing the volume work with KDE when using the scroll wheel above the icon?
- Does KDE show both the info popup and a tooltip with the patch applied (worse behavior than before)?

Thanks for feedback.

info-popup

**Comment by jlindgren90** [comment]
To test XEmbed, try `lxpanel` (the old GTK version, not lxqt-panel). Here it shows a double tooltip:
image

**Comment by jlindgren90** [comment]
This seems to fix the double-tooltip issue:
```
diff --git a/src/statusicon-qt/statusicon.cc b/src/statusicon-qt/statusicon.cc
index e22bbe143..c976b3bde 100644
--- a/src/statusicon-qt/statusicon.cc
+++ b/src/statusicon-qt/statusicon.cc
@@ -164,7 +164,10 @@ bool SystemTrayIcon::event (QEvent * e)
     {
     case QEvent::ToolTip:
         if (! aud_get_bool ("statusicon", "disable_popup"))
+        {
+            setToolTip(QString()); /* prevent double tooltip */
             audqt::infopopup_show_current ();
+        }
         return true;
 
     case QEvent::Wheel:
```

**Comment by radioactiveman** [comment]
Thanks John for testing and the double tooltip fix. Meanwhile I have tried it on macOS where the tooltip is shown now.

Happy New Year! :fireworks:

**Comment by bpanca05** [comment]
> @bpanca05: In your [bug report](https://github.com/orgs/audacious-media-player/discussions/93) I have seen you use KDE and also enabled the status icon plugin. Could you please answer my questions and try the patch from this pull request?
> 
>     * Does KDE show the info popup like in my screenshot below, a general tooltip like "Audacious" or no tooltip at all?
> 
>     * Does changing the volume work with KDE when using the scroll wheel above the icon?
> 
>     * Does KDE show both the info popup and a tooltip with the patch applied (worse behavior than before)?
> 
> 
> Thanks for feedback.
> 
> info-popup

Sorry for the late response, but before and after this commit merged, nothing change from status icon on KDE, it's simply say "Audacious" and no additional information like your attached image.

image

**Pull request merged**
