### PR TITLE
Use embedded lyrics from ID3 TAG

### PR DESCRIPTION
**Pull request by broiler315**
Why not to get Lyrics tag display support? I ported Fauxdacious lyricwiki plugin to display lyrics. There is my another another commit in the audacious core project, where I made the lyrics tag support.
Please, check this out.
Thank You!

### CODE REVIEW

**Comment by jlindgren90** [comment]
It looks like this overwrites/reverts changes that have been made in Audacious since the code was forked. The port will need to be done more carefully than this. It's not just a matter of copying the files from Fauxdacious.

Also, please split up the changes into smaller commits rather than one mega-commit, with the changes explained in the commit messages.

**Comment by broiler315** [comment]
This commit was an example of using embedded Lyrics tag. I don't know what plans have the Audacious Community to the LyricWiki plugin. In my opinion the result should be formed in this way. 

Preferences window should have some base options and the table of URL templates with their priorities :
1) check-box - use Embedded Lyrics (from Lyrics tag) 
2) table with providers and their priority (copied some data from neighboring branch)
 providerName fetchUrl
 MyProviderN1 "http://api.chartlyrics.com/apiv1.asmx/SearchLyricDirect?artist=${ARTIST/ /%20}&song=${TITLE/ /%20}"
 MyProviderN2  "https://makeitpersonal.co/lyrics?artist=${ARTIST/ /%20}&title=${TITLE/ /%20}")
...
 MyProviderN++ <temlate of the url>
3) check-box: Save lyrics in local cache
4) check-box: Load lyrics from in local cache

The Lyrics window should have possibility to edit lyrics.
The right-click on this window should have an option to save the displayed lyrics to the mp3 file.

What do you think of this idea?

**Comment by jlindgren90** [comment]
A check-box to use embedded lyrics sounds good as a start. Would you be willing/able to create a pull request that adds only that (with of course the code to read the embedded lyrics) to start with? Other changes (like support for editing lyrics) could be left for a future pull request.

**Comment by broiler315** [comment]
Making a pull request with the only one feature ("check-box to use embedded lyrics") seems good to me. I can try to do it, but not immediately.

I need some time to understand how the plugin works. What IDE do you use to debug the project? Can you offer something instead of "debug printfs"?

**Comment by jlindgren90** [comment]
> I need some time to understand how the plugin works. What IDE do you use to debug the project? Can you offer something instead of "debug printfs"?

You can use `gdb` from the command-line (what I usually do) or any GDB front-end of your choice.

**Comment by broiler315** [comment]
Have you looked at my changes? The embedded lyrics display now works fine.

**Comment by jlindgren90** [comment]
@broiler315 The changes look okay at first glance, other than formatting. I am waiting for your response to my comments on https://github.com/audacious-media-player/audacious/pull/56.

**Comment by broiler315** [comment]
I've fixed some white-spaces according to the formatting style. Maybe something else?

**Comment by jlindgren90** [comment]
@broiler315 Thanks, formatting looks good now. I will give this a test once you've had a chance to respond to my review on https://github.com/audacious-media-player/audacious/pull/56 (sorry for the confusion again) and hopefully we can get this merged.

**Pull request closed without merging**
