### PR TITLE
simplify systray context menu

### PR DESCRIPTION
**Pull request by landroni**
This patch tries to simplify the systray icon context menu. One reason I like Audacious is that it largely keeps things simple, as in KISS, making for a smooth and non-confusing interface. This is why I would like to propose some simplifications to the current menus. 

To start, this patch removes Open Files and Settings items from the context menu. In my view the systray context menu for a player requires precisely two functions: Playback controls and Quit. If you need to Open Files, Add Files or access Settings, you will likely bring up the main window anyway. Unless the devels consider that these are oft-accessed items (or they use them regularly), I would propose to remove them from the menu. 

In the commits I simply commented out the relevant portions (so that they can be easily reenabled some later time if desired), but I can delete the lines if it's better. 

One thing I couldn't figure out is the Hide/Restore items in Qt. In principle I'd suggest removing those as well, but strangely Qt automatically makes the first two items in this menu behave like a toggle depending on whether the main window is visible / hidden. While this works for Hide/Restore, it breaks functionality for Play/Pause. Any ideas how to disable this behavior in Qt?

### CODE REVIEW

**Comment by landroni** [comment]
I see, makes sense. What about the Qt Hide/Restore toggle? I don't think it is too useful in terms of functionality...

**Comment by jlindgren90** [comment]
I'd be happy with removing that one.  Not only because it is redundant but also because the implementation is ugly.

**Comment by landroni** [comment]
I can do this if we could find a way to avoid Qt automatically making the first two items in the list a toggle...

**Comment by jlindgren90** [comment]
Are you sure it's Qt doing that?  I didn't write this code but I thought that it was StatusIcon::update_menu() implementing the toggle (by hiding one of two separate menu items).

**Comment by landroni** [comment]
I think you're right, but I'm constantly seeing this issue with the Qt5 interface (never with Gtk): Often the systray icon won't appear, but sometimes it does. Seems to be random. 

When `-VV`, here's the part that seems relevant: 

```
INFO plugin-registry.cc:544 [plugin_register]: Register plugin: /usr/local/lib/audacious/General/statusicon-qt.so
[...]
INFO plugin-init.cc:177 [start_plugins]: Starting Status Icon.
INFO plugin-load.cc:66 [plugin_load]: Loading plugin: /usr/local/lib/audacious/General/statusicon-qt.so.
DEBUG vfs.cc:178 [fseek]: <0x7f74a8001220> seek to 0 from beginning
DEBUG vfs.cc:178 [fseek]: <0x7f74a8001220> seek to 0 from beginning
DEBUG vfs.cc:213 [feof]: <0x7f74a8001220> eof = no
DEBUG vfs.cc:137 [fread]: <0x7f74a8001220> read 8192 elements of size 1 = 8192
DEBUG seekable_stream_callbacks.cc:153 [metadata_callback]: total_total_samples=11242560
DEBUG seekable_stream_callbacks.cc:156 [metadata_callback]: bits_per_sample=16
DEBUG seekable_stream_callbacks.cc:159 [metadata_callback]: channels=2
DEBUG seekable_stream_callbacks.cc:162 [metadata_callback]: sample_rate=44100
DEBUG vfs.cc:259 [fsize]: <0x7f74a8001220> size = 26331337
DEBUG seekable_stream_callbacks.cc:171 [metadata_callback]: bitrate=826297
DEBUG vfs.cc:213 [feof]: <0x7f74a8001220> eof = no
DEBUG vfs.cc:137 [fread]: <0x7f74a8001220> read 8192 elements of size 1 = 8192
DEBUG vfs.cc:198 [ftell]: <0x7f74a8001220> tell = 16384
DEBUG seekable_stream_callbacks.cc:80 [tell_callback]: Current position: 16384
DEBUG effect.cc:47 [effect_start]: Starting effects.
INFO output.cc:175 [setup_output]: Setup output, format 0, 2 channels, 44100 Hz.
INFO output.cc:469 [output_set_replay_gain]: Replay Gain info:
INFO output.cc:470 [output_set_replay_gain]:  album gain: 0.000000 dB
INFO output.cc:471 [output_set_replay_gain]:  album peak: 0.000000
INFO output.cc:472 [output_set_replay_gain]:  track gain: 0.000000 dB
INFO output.cc:473 [output_set_replay_gain]:  track peak: 0.000000
DEBUG vfs.cc:259 [fsize]: <0x7f74a8001220> size = 26331337
DEBUG seekable_stream_callbacks.cc:110 [length_callback]: Stream length is 26331337 bytes
DEBUG vfs.cc:178 [fseek]: <0x7f74a8001220> seek to 2006321 from beginning
INFO probe-buffer.cc:54 [release_buffer]: <0x7f74a8001220> buffering disabled for file:///tmp/path.flac
DEBUG vfs.cc:213 [feof]: <0x7f74a8001220> eof = no
DEBUG vfs.cc:137 [fread]: <0x7f74a8001220> read 8192 elements of size 1 = 8192
DEBUG vfs.cc:213 [feof]: <0x7f74a8001220> eof = no
DEBUG vfs.cc:137 [fread]: <0x7f74a8001220> read 8192 elements of size 1 = 8192
DEBUG vfs.cc:213 [feof]: <0x7f74a8001220> eof = no
DEBUG vfs.cc:137 [fread]: <0x7f74a8001220> read 8192 elements of size 1 = 8192
DEBUG vfs.cc:198 [ftell]: <0x7f74a8001220> tell = 2030897
DEBUG seekable_stream_callbacks.cc:80 [tell_callback]: Current position: 2030897
DEBUG vfs.cc:178 [fseek]: <0x7f74a8001220> seek to 2037036 from beginning
DEBUG vfs.cc:213 [feof]: <0x7f74a8001220> eof = no
DEBUG vfs.cc:137 [fread]: <0x7f74a8001220> read 8192 elements of size 1 = 8192
DEBUG vfs.cc:213 [feof]: <0x7f74a8001220> eof = no
DEBUG vfs.cc:137 [fread]: <0x7f74a8001220> read 8192 elements of size 1 = 8192
DEBUG vfs.cc:198 [ftell]: <0x7f74a8001220> tell = 2053420
DEBUG seekable_stream_callbacks.cc:80 [tell_callback]: Current position: 2053420
DEBUG vfs.cc:178 [fseek]: <0x7f74a8001220> seek to 2048286 from beginning
DEBUG vfs.cc:213 [feof]: <0x7f74a8001220> eof = no
DEBUG vfs.cc:137 [fread]: <0x7f74a8001220> read 8192 elements of size 1 = 8192
DEBUG vfs.cc:213 [feof]: <0x7f74a8001220> eof = no
DEBUG vfs.cc:137 [fread]: <0x7f74a8001220> read 8192 elements of size 1 = 8192
DEBUG vfs.cc:213 [feof]: <0x7f74a8001220> eof = no
DEBUG vfs.cc:137 [fread]: <0x7f74a8001220> read 8192 elements of size 1 = 8192
INFO plugin-init.cc:126 [start_required]: Starting selected interface plugin Qt Interface.
INFO plugin-load.cc:66 [plugin_load]: Loading plugin: /usr/local/lib/audacious/General/qtui.so.
INFO interface.cc:68 [interface_load]: Loading Qt Interface.
INFO interface.cc:85 [interface_unload]: Unloading Qt Interface.
INFO plugin-init.cc:222 [stop_plugins]: Shutting down Audio CD Menu Items.
INFO plugin-init.cc:222 [stop_plugins]: Shutting down MPRIS 2 Server.
INFO plugin-init.cc:222 [stop_plugins]: Shutting down Status Icon.
INFO plugin-init.cc:207 [stop_plugins]: Shutting down PulseAudio Output.
```

I don't see anything that might point to a problem. Could this be the fault of Xfce and its systray? I've noticed 'something' like this in the past, but I couldn't be sure. Otherwise, how else could I debug this?

**Pull request closed without merging**
